language: ruby
bundler_args: --without development
rvm:
  - "2.0.0"
gemfile: Gemfile.ci
env:
  - DB=postgresql
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - psql -c 'create database lbspen_test' -U postgres
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec